Feature/create anonymize customer without any orders
synolia/SyliusGDPRPlugin pull request #28
Opened 2021-09-01 07:25 UTC by GalloisLuca

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?   | no

2021-09-16 14:53 UTC, oallain commented on src/Processor/AdvancedActions/AnonymizeCustomersNotLoggedBeforeProcessor.php
> +            ->from(get_class($this->shopUserFactory->createNew()), 'su')
Shouldn't we use the `sylius.model.shop_user.class` parameter?

2021-09-16 14:53 UTC, oallain commented on src/Resources/translations/messages.en.yaml
>          execute: Execute
Can you add blank line at the end of files ?

2021-09-17 13:25 UTC, oallain approved these changes, later dismissed

2021-10-08 13:29 UTC, oallain requested changes

2021-10-08 13:29 UTC, oallain commented on src/DependencyInjection/CompilerPass/RegisterAdvancedActionsFormDataProcessorsPass.php
> + * This file is part of the Sylius package.
No 😉

2021-10-08 13:29 UTC, oallain commented on src/Processor/AdvancedActions/AnonymizeCustomersWithoutAnyOrdersBeforeProcessor.php
> +                if ($order->getState() === 'cart') {
```suggestion
                if ($order->getState() === OrderInterface::STATE_CART) {
```

2021-10-08 13:29 UTC, oallain commented on src/SynoliaSyliusGDPRPlugin.php
> +    public const VERSION = '1.1.0';
Can you remove it ?

2021-11-07 10:59 UTC, oallain approved these changes, later dismissed

2022-05-20 09:47 UTC, TheGrimmChester requested changes

2022-05-20 09:47 UTC, TheGrimmChester commented on src/Processor/AdvancedActions/AnonymizeCustomersNotLoggedBeforeProcessor.php
> +    private $parameterBag;
You can type hint that

2022-05-20 09:47 UTC, TheGrimmChester commented on src/Processor/AdvancedActions/AnonymizeCustomersWithoutAnyOrdersBeforeProcessor.php
> +    private $entityManager;
You can type hint that and all the others

2022-05-20 09:47 UTC, TheGrimmChester commented on tests/PHPUnit/Processor/AdvancedActions/AnonymizeCustomerWithoutAnyOrdersBeforeProcessorTest.php
> +    private $manager;
You can type hint that

2023-01-20 11:17 UTC, oallain submitted a review, later dismissed

2023-01-20 11:17 UTC, oallain commented on .gitignore
> +.idea/
Already on master, so you have a conflict, can you remove it?

2023-01-20 11:17 UTC, oallain commented on install/Application/.gitignore
> +.env.*.local
In .gitignore in root directory we have
`/tests/Application/`
so you need to remove this file.

2023-07-07 07:09 UTC, oallain approved these changes

2023-07-07 07:12 UTC, TheGrimmChester approved these changes

2023-07-07 07:15 UTC, merged

2023-07-07 07:16 UTC, oallain commented
Thanks @GalloisLuca and @tuyetrinhvo :rocket: