fix: add symfony/property-info in dependency
synolia/SyliusGDPRPlugin pull request #46
Opened 2022-10-10 12:57 UTC by flochntrl

| Q             | A
| ------------- | ---
| Bug fix?      | yes

Add the symfony/property-info in depency because we have a break in prod env.

2022-10-10 12:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/synolia/SyliusGDPRPlugin?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/synolia/SyliusGDPRPlugin?pullRequest=46) before we can accept your contribution.<br/><hr/>**syno_fcl** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/synolia/SyliusGDPRPlugin?pullRequest=46) it.</sub>

2022-10-10 18:52 UTC, oallain requested changes
Can you also sign CLA ?
Thanks @flochntrl

2022-10-10 18:52 UTC, oallain commented on composer.json
> +        "symfony/property-info": "^5.4"
```suggestion
        "symfony/property-info": "^4.4|^5.4"
```

2022-10-11 07:04 UTC, Jibbarth requested changes
I think in your case, the package [phpdocumentor/reflection-docblock](https://packagist.org/packages/phpdocumentor/reflection-docblock) should also be added, because it's not a direct dependency of [symfony/property-info](https://packagist.org/packages/symfony/property-info)

2022-11-08 16:15 UTC, oallain commented
Clove in favor of #48

2022-11-08 16:15 UTC, closed without merging